run:
  name:
  output_root: runs
  resume: false
  seed: 42

data:
  hla_seq_file: data/hla_dict/hla_full_seq_dict.txt
  train_file: data/small/small_train.txt
  pep_esm_file: data/pep/small_train_pep_esm.npy
  hla_esm_file: data/hla/small_train_hla_unique_esm.npy
  hla_esm_names_file: data/hla/small_train_hla_unique_names.npy

train:
  batch_size: 64
  num_epochs: 40
  valid_ratio: 0.1
  patience: 9

optimizer:
  name: Adadelta
  lr: 0.01
  weight_decay: 0.0001
